name: Publish

on:
  create:
    ref_type: 'tag'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.20.x

      - name: Deploy to nest.land
        run: |
          deno install -A --unstable https://x.nest.land/eggs@0.3.10/eggs.ts
          eggs link ${{ secrets.NESTAPIKEY }}
          eggs publish --yes --no-check --version $(git describe --tags $(git rev-list --tags --max-count=1))
